from .collapsible import CollapsibleWidget
from .prompts import PromptWidget
from .seed import SeedWidget
from .models import ModelsWidget
from .generate import GenerateWidget
from .image_in import ImageInWidget
from .denoise import DenoiseWidget
from .extensions import ExtensionWidget
from .mask import MaskWidget
from .color_correction import ColorCorrectionWidget
from .batch import BatchWidget
from .hires_fix import HiResFixWidget
from .cfg import CFGWidget
from .interrogate import InterrogateWidget